# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Build and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_test:
    name: Build and Test on Ruby ${{ matrix.ruby-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby-version: ['2.5', '2.6', '2.7']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Execute Ruby unit tests with code coverage
      if: matrix.ruby-version == '2.6'
      env:
        COVERAGE: true
      run: bundle exec rake test:unit
    - name: Execute Ruby unit tests
      if: matrix.ruby-version != '2.6'
      run: bundle exec rake test:unit
