# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run integration tests with Rake

name: Run Integration Tests

# Every Sunday at 8PM
on:
  schedule:
    - cron: "0 20 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  integration_test:
    name: Build and Run Integration Tests on Ruby ${{ matrix.ruby-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby-version: ['2.7']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Execute Ruby integration tests
      env:
        NATURAL_LANGUAGE_CLASSIFIER_APIKEY: ${{ secrets.NLC_APIKEY }}
        NATURAL_LANGUAGE_CLASSIFIER_URL: "https://api.us-south.natural-language-classifier.watson.cloud.ibm.com"
        LANGUAGE_TRANSLATOR_APIKEY: ${{ secrets.LT_APIKEY }}
        LANGUAGE_TRANSLATOR_URL: "https://api.us-south.language-translator.watson.cloud.ibm.com"
        NATURAL_LANGUAGE_UNDERSTANDING_APIKEY: ${{ secrets.NLU_APIKEY }}
        NATURAL_LANGUAGE_UNDERSTANDING_URL: "https://api.us-south.natural-language-understanding.watson.cloud.ibm.com"
        PERSONALITY_INSIGHTS_APIKEY: ${{ secrets.PI_APIKEY }}
        PERSONALITY_INSIGHTS_URL: "https://api.us-south.personality-insights.watson.cloud.ibm.com"
        TONE_ANALYZER_APIKEY: ${{ secrets.TA_APIKEY }}
        TONE_ANALYZER_URL: "https://api.us-south.tone-analyzer.watson.cloud.ibm.com"
        SPEECH_TO_TEXT_APIKEY: ${{ secrets.STT_APIKEY }}
        SPEECH_TO_TEXT_URL: "https://api.us-south.speech-to-text.watson.cloud.ibm.com"
        TEXT_TO_SPEECH_APIKEY: ${{ secrets.TTS_APIKEY }}
        TEXT_TO_SPEECH_URL: "https://api.us-south.text-to-speech.watson.cloud.ibm.com"
        VISUAL_RECOGNITION_APIKEY: ${{ secrets.VR_APIKEY }}
        VISUAL_RECOGNITION_COLLECTION_ID: ${{ secrets.VR_COLLECTION_ID }}
        VISUAL_RECOGNITION_URL: "https://api.us-south.visual-recognition.watson.cloud.ibm.com"
        COMPARE_COMPLY_APIKEY: ${{ secrets.CC_APIKEY }}
        COMPARE_COMPLY_FEEDBACK_ID: ${{ secrets.CC_FEEDBACK_ID }}
        COMPARE_COMPLY_URL: "https://api.us-south.compare-comply.watson.cloud.ibm.com"
        ASSISTANT_APIKEY: ${{ secrets.WA_APIKEY }}
        ASSISTANT_WORKSPACE_ID: ${{ secrets.WA_WORKSPACE_ID }}
        ASSISTANT_ASSISTANT_ID: ${{ secrets.WA_ASSISTANT_ID }}
        ASSISTANT_URL: "https://api.us-south.assistant.watson.cloud.ibm.com"
        DISCOVERY_APIKEY: ${{ secrets.D1_APIKEY }}
        DISCOVERY_ENVIRONMENT_ID: ${{ secrets.D1_ENVIRONMENT_ID }}
        DISCOVERY_COLLECTION_ID: ${{ secrets.D1_COLLECTION_ID }}
        DISCOVERY_URL: "https://api.us-south.discovery.watson.cloud.ibm.com"
        DISCOVERY_V2_APIKEY: ${{ secrets.D2_APIKEY }}
        DISCOVERY_V2_PROJECT_ID: ${{ secrets.D2_PROJECT_ID }}
        DISCOVERY_V2_COLLECTION_ID: ${{ secrets.D2_COLLECTION_ID }}
        DISCOVERY_V2_URL: "https://api.us-south.discovery.watson.cloud.ibm.com"
      run: bundle exec rake test:integration

    - name: Notify slack on success
      if: false # success()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        status: SUCCESS
        color: good

    - name: Notify slack on failure
      if: failure()
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        status: FAILED
        color: danger