# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run integration tests with Rake

name: Run Integration Tests

# Every Sunday at 8PM
on:
  push:
    branches: [ '**' ]
  schedule:
    - cron: "0 20 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      slackMess:
        description: 'Send Slack Notification'
        required: true
        default: true

jobs:
  integration_test:
    name: Build and Run Integration Tests on Ruby ${{ matrix.ruby-version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ruby-version: ['2.7']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Execute Ruby integration tests
      env:
        NATURAL_LANGUAGE_CLASSIFIER_APIKEY: ${{ secrets.NLC_APIKEY }}
        NATURAL_LANGUAGE_CLASSIFIER_URL: "https://api.us-south.natural-language-classifier.watson.cloud.ibm.com"
      run: bundle exec rake test:integration

    - name: Notify slack on success
      if: ${{ success() && github.event.inputs.slackMess == true }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        status: SUCCESS
        color: good

    - name: Notify slack on failure
      if: ${{ failure() && github.event.inputs.slackMess == true }}
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
      uses: voxmedia/github-action-slack-notify-build@v1
      with:
        channel: watson-e2e-tests
        status: FAILED
        color: danger